image:
  registry: docker.io
  repository: nginxinc/nginx-unprivileged
  tag: "stable-alpine"
  pullPolicy: IfNotPresent

replicaCount: 1
revisionHistoryLimit: 3

rollingUpdate:
  maxUnavailable: 25%
  maxSurge: 25%

containerPorts:
  http: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort:
    http: 8080

gatewayApi:
  enabled: false
  gatewayName: ""
  gatewayNamespace: ""
  httpsSectionName: ""
  httpSectionName: ""
  redirectToHttps: false
  hostnames: []
  rules: []

env: {}
extraEnv: []

imagePullSecrets: []

podLabels: {}

podSecurityContext: {}
securityContext: {}

startupProbe: {}
readinessProbe: {}
livenessProbe: {}

resources: {}

volumes: []
volumeMounts: []
