image:
  registry: docker.io
  repository: d4vlin/firewall-service
  tag: "uat-20260203-135416"

containerPorts:
  http: 8080

replicaCount: 2

service:
  type: ClusterIP
  port: 8080
  targetPort:
    http: 8080

env:
  LOG_LEVEL: "info"
  ADMIN_ENABLED: "false"

  # TI: public replica=2 -> tắt để tránh chạy job trùng
  TI_ENABLED: "true"
  TI_DAILY_RECHECK_ENABLED: "true"

  # Optional
  METRICS_ENABLED: "false"
  TRACING_ENABLED: "false"

extraEnv:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: firewall-integration-env
        key: DATABASE_URL
  - name: API_KEY_PEPPER
    valueFrom:
      secretKeyRef:
        name: firewall-integration-env
        key: API_KEY_PEPPER

podLabels: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

gatewayApi:
  enabled: true
  gatewayName: traefik-gateway
  gatewayNamespace: traefik

  httpsSectionName: websecure
  httpSectionName: web
  redirectToHttps: true

  hostnames:
    - api.uat.local

  rules:
    - pathPrefix: /
      serviceName: firewall-integration
      servicePort: 8080
