image:
  registry: docker.io
  repository: d4vlin/firewall-service
  tag: "uat-20260203-074339"

containerPorts:
  http: 8080

replicaCount: 2

service:
  type: ClusterIP
  port: 8080
  targetPort:
    http: 8080

env:
  LOG_LEVEL: "info"
  ADMIN_ENABLED: "false"

  # TI: public replica=2 -> tắt để tránh chạy job trùng
  TI_ENABLED: "false"
  TI_DAILY_RECHECK_ENABLED: "false"

  # Performance & Audit (Theo khuyến nghị)
  AUDIT_ENABLED: "false"
  LAST_USED_UPDATE_MIN_INTERVAL_SECONDS: "900"

  # Optional
  METRICS_ENABLED: "false"
  TRACING_ENABLED: "false"

extraEnv:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: firewall-integration-env
        key: DATABASE_URL
  - name: API_KEY_PEPPER
    valueFrom:
      secretKeyRef:
        name: firewall-integration-env
        key: API_KEY_PEPPER

# Security Context chuẩn Kyverno & Best Practice
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true # Đã an toàn vì Chart có mount /tmp

podLabels: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

gatewayApi:
  enabled: true
  gatewayName: traefik-gateway
  gatewayNamespace: traefik

  httpsSectionName: websecure
  httpSectionName: web
  redirectToHttps: true

  hostnames:
    - api.uat.local

  rules:
    - pathPrefix: /
      serviceName: firewall-integration # NHỚ CHECK LẠI TÊN SERVICE SAU KHI SYNC
      servicePort: 8080
